spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debproject1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: carlos
    password: '1234' 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
